- rusty-machine/src/learning/gp.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/learning/optim/fmincg.rs
- rusty-machine/src/learning/optim/grad_desc.rs
- rusty-machine/src/linalg/matrix.rs
- rusty-machine/src/linalg/vector.rs
- rusty-machine/tests/learning/k_means.rs
- rusty-machine/tests/linalg/mat.rs
This PR will resolve issue #1 by making the current data field private. This PR includes two new methods:
- data() : a public method returning a reference to the underlying data.
- into_vec() : a public method which consumes self and returns the underlying data.
> Making matrix and vector data private.

- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/vector.rs
The [std::fmt documentation recommends](https://doc.rust-lang.org/std/fmt/#fmtdisplay-vs-fmtdebug) implementing a faithful representation of internal state for all public types.
Consider the following program.
``` rust
extern crate rusty_machine;
use rusty_machine::linalg::matrix::Matrix;
use rusty_machine::linalg::vector::Vector;
fn main() {
let my_first_matrix = Matrix::new(2, 3, vec![1, 2, 3, 4, 5, 6]);
let my_first_vector = Vector::new(vec![1, 2, 3, 4]);
println!("{:?}", my_first_matrix);
println!("{:?}", my_first_vector);
}
```
**On master:**
*[fails to compile]*
```
src/main.rs:9:22: 9:37 error: the trait `core::fmt::Debug` is not implemented for the type `rusty_machine::linalg::matrix::Matrix<_>` [E0277]
src/main.rs:9     println!("{:?}", my_first_matrix);
^~~~~~~~~~~~~~~
[redacted …
```
> derive Debug for Matrix and Vector

- rusty-machine/src/linalg/matrix/mod.rs
Users of a linear algebra library might occasionally want to pretty-print a matrix!
``` rust
use rusty_machine::linalg::matrix::Matrix;
fn main() {
let m = Matrix::new(3, 3, (1..10).collect::<Vec<_>>());
println!("{}", m);
}
// outputs:
//
// ⎡1 2 3⎤
// ⎢4 5 6⎥
// ⎣7 8 9⎦
```
> implement fmt::Display for Matrix

- rusty-machine/src/learning/glm.rs
- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/learning/gp.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/logistic_reg.rs
- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/learning/optim/fmincg.rs
- rusty-machine/src/learning/optim/grad_desc.rs
- rusty-machine/src/learning/svm.rs
- rusty-machine/src/learning/toolkit/activ_fn.rs
- rusty-machine/src/learning/toolkit/cost_fn.rs
- rusty-machine/src/learning/toolkit/kernel.rs
- rusty-machine/src/lib.rs
Herein:
* remaining `derive(Debug)` attributes, a sequel to #18  
* activating the missing-`Debug` lint at `warn` level
* `derive(Copy, Clone)` attributes where applicable ("[Generally speaking,](https://doc.rust-lang.org/std/marker/trait.Copy.html#when-should-my-type-be-copy) if your type can implement Copy, it should.")
> Derive the World

- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/linalg/matrix/mod.rs
Modified `mut_data` method for matrices to return a mutable slice instead of a vector.
This PR will solve issue #24
> Mutable mat data

- rusty-machine/benches/linalg/matrix.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/utils.rs
- rusty-machine/src/linalg/vector.rs
- rusty-machine/tests/linalg/mat.rs
- rusty-machine/tests/linalg/vector.rs
This solves (largely) issue #26 . It also includes some improvements in terms of vectorization and code re-usability.
The PR includes changes to the underlying binary data operations (sum, subtract, element-wise multiplication, etc.). It also reuses memory when one of the incoming arguments is to be consumed (and has the appropriate size).
One aspect ignored in this PR is the reassignment of matrix data during square matrix multiplication. I figured this is a rare case in the problem domain but should be introduced later.
test linalg::matrix::empty                                 ... bench:               0 ns/iter (+/- 0)
test linalg::matrix::mat_create_100_100         ... bench:        2,734 ns/iter (+/- 254)
test linalg::matrix::mat_create_add_100_100 ... bench:        8,113 ns/iter …
> Memory alloc

- .gitignore
- rusty-machine/src/learning/k_means.rs
Add a constructor with specified values for all options for the KMeansClassifier. In addition, add setters for each field. Not super attached to any of the components of the patch besides `KMeansClassifier::new_specified`. I also added some rules to `.gitignore` for the sanity of vim users :smile:
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/athemathmo/rusty-machine/30)
> Add setters and a specified constructor: kmeans

- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
This PR is to complete issue #22 . It introduce two new structs, the `MatrixSlice` and `MatrixSliceMut` - the full spec and details for these can be found in issue #22 - though the actual implementation details differ slightly (we use raw pointers instead).
The PR also adds some housekeeping for operations overloading using macros. This is relevant for issue #29 .
Additionally we add an `Axes` enum to the `matrix` module. This can also be used to clean up the `mean` and `variance` methods for `Matrix`. We have also provided iterators for the `MatrixSlice` and `MatrixSliceMut` which was not a strict requirement of #22.
Though all of the specified functionality in the original issue has been covered there are some items which may be good for future fulfillment. These include:
- Transposing …
> MatrixSlice and MatrixSliceMut

- README.md
- rusty-machine/src/learning/naive_bayes.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/matrix/mod.rs
Adding a simple implementation of Naive Bayes Classifiers. Only support single pass training.
This PR includes Gaussian, Multinomial and Bernoulli models. The following have not been included in this PR but would be nice:
- Checking model inputs (Bernoulli is flags, Multinomial is counts, etc.).
- Allowing specification of pseudo counts on the discrete models.
- Partial training (so we can go in batches).
If anyone has suggestions on how we can tackle these as part of this PR I'd be happy to hear it!
> Adding Naive Bayes Classifiers

- rusty-machine/Cargo.toml
- rusty-machine/benches/linalg/matrix.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/matrix/decomposition.rs
- rusty-machine/src/linalg/matrix/impl_ops.rs
- rusty-machine/src/linalg/matrix/mat_mul.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/utils.rs
This gives us huge speedups for matrix multiplication:
> Before:
> 
> test linalg::matrix::mat_mul_128_1000 ... bench: 14,231,183 ns/iter (+/- 833,129)
> 
> After:
> 
> test linalg::matrix::mat_mul_128_1000 ... bench: 3,352,754 ns/iter (+/- 412,408)
This change only applies for f32 and f64 multiplication. The PR adds some more complex trait bounds (requiring `Any` on many implementation blocks). Once specialization lands this can be removed.
This resolve #38 .
> Matrixmultiply

- rusty-machine/src/linalg/matrix/mat_mul.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
Fixing bug with MatrixSlice multiplication. Adding more test coverage.
> Using row-stride with matrixmultiply

- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/vector.rs
Any reason not to do this?
(Previously—
```
<std macros>:5:8: 5:18 error: binary operation `==` cannot be applied to type `linalg::matrix::Matrix<_>` [E0369]
<std macros>:5 if ! ( * left_val == * right_val ) {
^~~~~~~~~~
src/linalg/matrix/mod.rs:1190:9: 1190:32 note: in this expansion of assert_eq! (defined in <std macros>)
<std macros>:5:8: 5:18 help: run `rustc --explain E0369` to see a detailed explanation
<std macros>:5:8: 5:18 note: an implementation of `std::cmp::PartialEq` might be missing for `linalg::matrix::Matrix<_>`
<std macros>:5 if ! ( * left_val == * right_val ) {
^~~~~~~~~~
src/linalg/matrix/mod.rs:1190:9: 1190:32 note: in this expansion of assert_eq! (defined in <std macros>)
```
)
> derive PartialEq for Matrix and Vector

- rusty-machine/src/linalg/matrix/impl_ops.rs
This resolves issue #42 .
This PR introduces OpAssign for:
- `Matrix`.op_assign(scalar)
- `MatrixSliceMut`.op_assign(scalar)
- `Matrix` += OR -= `Matrix`
- `Matrix` += OR -= `MatrixSlice`
- `Matrix` += OR -= `MatrixSliceMut`
- `MatrixSliceMut` += OR -= `Matrix`
- `MatrixSliceMut` += OR -= `MatrixSlice`
- `MatrixSliceMut` += OR -= `MatrixSliceMut`
The macros can probably be cleaned up. Additionally the tests could probably use macros to make them shorter...
> Implementing OpAssign overloading and tests

- rusty-machine/src/linalg/matrix/impl_ops.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
- rusty-machine/src/linalg/vector.rs
Arguments in favor:
* Flexibility! You have the option of passing a slice (or anything else that implements `Into<Vec<T>>`) and letting `new` allocate its own vector.
Arguments against:
* type inference doesn't work as well: notice how this commit had to add several turbofish operators to tests.
* rebuttal: actual users mostly aren't going to be getting their data from `.collect()`, right?
> Matrix and Vector constructors accept data as Into<Vec<T>>?

- rusty-machine/src/linalg/matrix/impl_ops.rs
- rusty-machine/tests/learning/gp.rs
The augmented-assignment tests in particular generated a lot of
unused-variable and unused-assignment warnings, which are undesirable
not only on æsthetic developer-experience grounds but, more importantly,
because genuinely useful warnings inadvertently set off by future
development efforts could get lost in the noise. Typically one would
indicate an intentionally-unused variable by choosing an identifier
starting with an underscore, but in the case of the augmented-assignment
tests, the `allow`-directive attributes seem more appropriate: the
`a_slice` variables weren't _really_ unused; it's just that `rustc`
isn't smart enough to notice that they're views into an underlying
matrix which is being used.
> clean up compiler warnings

- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/learning/toolkit/regularization.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
This resolves issue #67 .
This PR includes a new `regularization` module. The module provides implementations of L1, L2 and Elastic Net regularization.
The regularization is only implemented within the Neural Networks. It provides some much needed numerical stability there. The construction of the module should allow it to be easily implemented in the other modules that require.
_Note: For linear regression we can solve the L2 Regularization analytically. Other than this we should be able to add regularization easily._
> Regularization

- rusty-machine/src/learning/toolkit/regularization.rs
- rusty-machine/src/linalg/matrix/decomposition.rs
- rusty-machine/src/linalg/matrix/impl_ops.rs
- rusty-machine/src/linalg/matrix/iter.rs
- rusty-machine/src/linalg/matrix/mat_mul.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
This resolves issue #70 . This PR adds life times to the `MatrixSlice` and `MatrixSliceMut` by using `PhantomData` markers.
There is a lot of code change attached which can be broken down into one of the following:
- Fixing trait implementations to include lifetimes.
- Adding new macros to differentiate between `Matrix` with no lifetimes and `MatrixSlice`.
- Fixing tests which were breaking borrowing rules (but compiled before).
> Slice markers

- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/convert.rs
`std::convert` provides slick `From` and `Into` traits for converting between types (and implementing `From` automatically gives you `Into`); we could be making more use of them (in addition to accepting U: Into<Vec<T>> as initialization data, as seen in #53) in the following two ways—
* By implementing `From<Vector<T>>` for `Matrix<T>`, we can convert vectors to _n_-by-1 matrices, which is often a worthwhile way of thinking about them.
* We can replace our `into_matrix` methods for matrix slices with `From`/`Into`. (Although a counterargument against this is that type inference can't always infer what you mean by `my_slice.into()`, whereas `my_slice.into_matrix()` didn't have that problem. Also, if we were going to do this, one might expect us to also similarly replace the `into_vec` …
> Into<Matrix> and From<>-for-Matrix, for Vector and matrix slices

- rusty-machine/src/learning/gmm.rs
Fixing bug with diagonal covariance options - the weight factor was not included.
Also added a new constructor that allows the user to specify the prior mixture weights.
> Fixing diagonal cov option bug. Adding gmm constructor

- rusty-machine/src/linalg/matrix/mod.rs
This was suggested in #85 
I'm not sure if it was worth it to pull out the `t[j] `outside of the `match` what is your opinion?
> Use unsafe set_len and direct indexing in variance

- rusty-machine/src/linalg/vector.rs
Macros and tests copied from matrix/impl_ops
Except from changing the names and replacing `Matrix` with `Vector` the macros and tests are almost identical with the original.
> Implement OpAssign traits for Vector #86

- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/logistic_reg.rs
- rusty-machine/src/learning/naive_bayes.rs
More methods provided by Option can be used this way
Fixes #92 
Should the documentation `Returns a reference to the Option<...>` also be changed?
> Use Option<&Type> instead of &Option<Type>

- rusty-machine/src/linalg/matrix/iter.rs
- rusty-machine/src/linalg/matrix/slice.rs
Fixes part of #94 but first I want to discuss some things with this implementation.
1. I changed `MatrixSlice.iter()` to take an external lifetime bound. It seems to compile this way but I'm not sure if it is correct. This was necessary since the deducted lifetime was invalid `into_iter` takes `self` as `Self` and so the borrowed value was only alive inside the method.
2. I duplicated the implementation for all three cases `value`, `&` and `&mut` this could surly be solved with some macro-magic. Would be nice if someone could help me there.
3. I'm not sure how to test this. The only thing that comes in mind is that I could manually iterate and check each value individually but that seems like a lot of duplicated code.
Small compile test
```rust
fn into_test() { 
let a = Matrix::new(3, 3, …
```
> Implement IntoIterator for MatrixSlice

- rusty-machine/src/learning/error.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/lib.rs
- rusty-machine/tests/learning/k_means.rs
This PR should resolves #82 and part of #81 .
It adds a new error handling module which will allow us to utilize results readily through the learning module. I kept this error module to just the learning side of rusty-machine as I plan to pull the linalg part into a new crate soon<sup>tm</sup>.
It also restructures the K-Means module by providing a trait for the initialization algorithm. This has the benefit of providing more flexibility to the user. The downside is an arguably more complex interface (not convinced of this). And more importantly we lose the Builder model we had before - this is because the type of the initialization algorithm must be confirmed as soon as we create the struct.
The above means some breaking changes to K-means. In addition to that described above I have made …
> K means and error handling

- src/learning/nnet.rs
Small rewrite of nnet module.
- in `create_weights`: use `rand::distributions::range::Range` as [advised on rand doc](https://doc.rust-lang.org/rand/rand/trait.Rng.html#method.gen_range)
- removed `initialize_weights` function and put the logic directly in `create_weights`
- in `compute_grad`: remove an  unecessary intermediary `grad` vector. On my very unscientific test, running the example `nnet-and_gate` is 2.5 % faster.
> Nnet rewrite

- src/learning/dbscan.rs
- src/learning/gmm.rs
- src/learning/gp.rs
- src/learning/naive_bayes.rs
- src/learning/optim/fmincg.rs
- src/learning/optim/grad_desc.rs
- src/learning/svm.rs
- src/learning/toolkit/regularization.rs
Partly closes #93 
I greped `data()` to search for relevant lines. 
Replace with `iter_rows` and `select_rows` whenever I could.
Also sometimes use `zip` iterator instead of `enumerate`. Hopefully it'll lead to less bound checks.
> Use more `iter_rows` and `select_rows`

- Cargo.toml
- src/learning/dbscan.rs
- src/learning/gmm.rs
- src/learning/k_means.rs
- src/learning/naive_bayes.rs
Partly closes #110 
Made some minor rewriting, I can roll them back if needed.
Also changed one signature on `Distribution` trait
```rust
fn update_params(&mut self, data: &Matrix<f64>, class: usize)
```
The fn now borrows `data` instead of taking ownership (there were no functional reason I think).
For the remaining `select_rows` one pattern that appears a lot is repeating one particular row and then doing matix operations with it. It looked like a good thing to do so I didn't touch it (I don't know how fast matrix operation is compared to a regular for loop).
> Remove several select_rows

- examples/k-means_generating_cluster.rs
- examples/nnet-and_gate.rs
- examples/svm-sign_learner.rs
- src/learning/dbscan.rs
- src/learning/error.rs
- src/learning/glm.rs
- src/learning/gmm.rs
- src/learning/gp.rs
- src/learning/k_means.rs
- src/learning/lin_reg.rs
- src/learning/logistic_reg.rs
- src/learning/naive_bayes.rs
- src/learning/nnet.rs
- src/learning/svm.rs
- src/lib.rs
- tests/learning/dbscan.rs
- tests/learning/gp.rs
- tests/learning/k_means.rs
- tests/learning/lin_reg.rs
This PR adds some error handling to the `SupModel` and `UnSupModel` traits. It's flagged as WIP as I have a few tweaks planned - but the core content is ready for review and I'd appreciate some feedback.
Note that I haven't attempted to cover all possible panics from within the `train` and `predict` functions. I think it is non-trivial to decide when such things should occur and so I'd prefer to take a lightweight approach for now and add them in as we go (as this will not cause breakage in the api). With that said - if you see something that should be returning an `Error` here please comment so I can address/create an issue.
> Adding error handling to model traits

- src/analysis/cross_validation.rs
- src/analysis/score.rs
- src/lib.rs
Not ready to merge yet, but wanted to get a bit of feedback.
The main issue at the moment is that we allocate fresh matrices for each of the k times we train and validate. As discussed previously, we should be able to allocate once and reuse the allocation for each of the folds. However, this would require the inputs and targets of k_fold_validate to be MatrixSlices, and I don't think any of the existing models support this yet.
The other issue is that there's a lot of boilerplate here to avoid allocating or copying when creating the indices for training and testing on for each fold, which seems a bit overkill given all the work we do to copy all the sample data around (even if we manage to get rid of the allocations in copy_rows).
Finally, we might want to run this in parallel, but then …
> Add cross validation

- Cargo.toml
- benches/examples/k_means.rs
- examples/k-means_generating_cluster.rs
- src/data/transforms/minmax.rs
- src/data/transforms/standardize.rs
- src/learning/dbscan.rs
- src/learning/glm.rs
- src/learning/gmm.rs
- src/learning/gp.rs
- src/learning/k_means.rs
- src/learning/lin_reg.rs
- src/learning/logistic_reg.rs
- src/learning/naive_bayes.rs
- src/learning/nnet.rs
- src/learning/optim/grad_desc.rs
- src/learning/svm.rs
- src/learning/toolkit/cost_fn.rs
- src/learning/toolkit/regularization.rs
- src/lib.rs
- src/prelude.rs
This will resolve PR #117 .
This continues the great work by @tafia by taking into account new breaking changes from both rusty-machine ( #120 ) and rulinalg (variance returns result).
The changes are mostly minor - modifying imports. There are some structural changes to naive bayes to help error propagation. There is also a performance regression on the neural nets but this has been discussed in #117 . The short of it is:
- `apply` is less efficient but there is an issue on rulinalg.
- `hcat` is less efficient on narrow matrices (as in the example) but more efficient on wide ones.
We are also making modifications to the neural nets with #126 which will provide big performance gains.
> Updating to Rulinalg 0.3.2

- src/data/transforms/minmax.rs
- src/data/transforms/mod.rs
- src/data/transforms/shuffle.rs
- src/data/transforms/standardize.rs
This PR adds a `Shuffler` transformer to the `data/transforms` module and resolves #127. I've also separated the `Transformer` trait into `Transformer` and `Invertible`. We require an additional trait import to use the `inv_transform` but otherwise things are unchaged. This lets us define transformers which cannot be inverted.
The intention is that this transformer can be directly used by users to shuffle their input data before running the model. We _could_ also use this transformer within the cross-validation and other modules.
I think that this module _should not_ be used within the `learning` module - this is because the transformer consumes the input data.
> Shuffler Transformer

- benches/examples/cross_validation.rs
- benches/lib.rs
Results on my machine (2.5 GHz Intel Core i7, 16 GB 1600 MHz DDR3):
```
running 4 tests
test examples::cross_validation::bench_1000_10_10  ... bench:     365,266 ns/iter (+/- 30,927)
test examples::cross_validation::bench_1000_10_100 ... bench:   3,708,769 ns/iter (+/- 1,097,906)
test examples::cross_validation::bench_1000_10_3   ... bench:     144,208 ns/iter (+/- 35,749)
test examples::cross_validation::bench_10_10_3     ... bench:       2,036 ns/iter (+/- 415)
```
> Add cross-validation benchmarks

- src/data/transforms/minmax.rs
- src/data/transforms/mod.rs
- src/data/transforms/shuffle.rs
- src/data/transforms/standardize.rs
Based on the discussion in #158, added ``.fit`` method to ``Transformer``. This also allows basic transformers to fit to training data and transform test data.
Needs to decide:
- ``Shuffler`` doesn't needs to be ``fit``. There is an option to split ``Transformer`` depending on needs to fit, but I feel it is complex rather than convenient from user's point of view.
- To keep backward compat, ``.transform`` internally calls ``.fit`` if it is not fitted yet. Or should this be breaking change to force users to call ``.fit`` first.
- Is it ok to change ``MinMaxScaler`` to store trained data as ``Vector`` rather than ``Vec``, which should be compat with others.
Once decisions are made, let me add tests to validate changes.
> Add Transformer.fit

- src/data/transforms/mod.rs
- src/data/transforms/normalize.rs
This work was started by @sinhrks . After breaking a rebase it was easier to move to a new branch... (sorry!)
> Adding normalizer transformation

- src/learning/lin_reg.rs
- tests/learning/lin_reg.rs
Before Linear Regressor would panic on ill-conditioned data, now it actually returns it as a result.
> Linear Regressor now returns error instead of panicking

- CONTRIBUTING.md
The link in the contributing file points to a dead link, which is inconsistent with the link in the main README.md file, which seems to work.  So just making a simple tweak to the CONTRIBUTING.md file =)
> Fix link to API documentation in contributing.md
