AtheMathmo/rusty-machine

- rusty-machine/src/learning/gp.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/learning/optim/fmincg.rs
- rusty-machine/src/learning/optim/grad_desc.rs
- rusty-machine/src/learning/toolkit/cost_fn.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/matrix.rs
- rusty-machine/tests/learning/gp.rs
- rusty-machine/tests/learning/k_means.rs
- rusty-machine/tests/learning/lin_reg.rs
I updated he ambiguous naming of variables. check it out.  if there is a problem tell me i am also new to rust  :) - This will fix issue #3
> ambiguous naming fix

- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/toolkit/cost_fn.rs
- rusty-machine/tests/learning/lin_reg.rs
Improvements to linear regression. This closes issue #5
> Linear regression

- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/logistic_reg.rs
- rusty-machine/src/learning/nnet.rs
This resolves issue #9 .
The main contribution of this PR is a new code structure for gradient optimized models that gives the user more control over the GD algorithm used. The details are discussed in the issue.
> Restructuring optimization traits

- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/learning/toolkit/rand_utils.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/matrix/mod.rs
This pull request brings a basic working GMM implementation.
The implementation provides a GMM with different options for covariances (diagonal, regularized or full). The EM algorithm uses the log likelihood as a stopping condition.
The current implementation definitely has areas that need improvement. Notable areas include:
- Performance of the EM algorithm.
- Initialization of the algorithm.
And there are bound to be other areas. Feedback welcome!
> Adding GMMs to rusty-machine

- rusty-machine/src/lib.rs
- rusty-machine/src/prelude.rs
> Adding prelude. Resolves issue #31.

- rusty-machine/src/linalg/matrix/decomposition.rs
> correct eigenmethods for (very) small matrices

- rusty-machine/src/linalg/matrix/iter.rs
- rusty-machine/src/linalg/matrix/mod.rs
This is to resolve issue #48 .
> Adding row iterators for each matrix struct.

- rusty-machine/src/linalg/matrix/slice.rs
> Making iterator pointers safer

- rusty-machine/src/learning/naive_bayes.rs
> avoid updating distribution params for empty class vectors : #63

- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/vector.rs
This relates to issue #32 . I'm anxious to say it completely resolves this issue but it is certainly a big step in the right direction!
> Removing unneeded trait bounds for Matrix and Vector

- rusty-machine/src/learning/optim/grad_desc.rs
- rusty-machine/src/learning/toolkit/rand_utils.rs
- rusty-machine/src/learning/toolkit/regularization.rs
- rusty-machine/src/linalg/vector.rs
- rusty-machine/tests/learning/optim/grad_desc.rs
- rusty-machine/tests/lib.rs
This PR includes several changes to the existing gradient descent algorithms and adds the AdaGrad algorithm. There are also some changes elsewhere providing support for this PR, i.e. Fisher-Yates shuffling.
It includes a breaking change: the GD algorithms no longer have all public fields and the `new` methods allow only valid inputs.
> Grad desc conditions

- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/linalg/convert.rs
> Adding `get mixture weights` to GMM

- rusty-machine/src/learning/glm.rs
- rusty-machine/src/learning/gmm.rs
- rusty-machine/src/learning/gp.rs
- rusty-machine/src/learning/k_means.rs
- rusty-machine/src/learning/lin_reg.rs
- rusty-machine/src/learning/logistic_reg.rs
- rusty-machine/src/learning/naive_bayes.rs
- rusty-machine/src/learning/nnet.rs
- rusty-machine/src/learning/optim/fmincg.rs
- rusty-machine/src/learning/optim/grad_desc.rs
- rusty-machine/src/learning/svm.rs
- rusty-machine/src/learning/toolkit/activ_fn.rs
- rusty-machine/src/learning/toolkit/cost_fn.rs
- rusty-machine/src/learning/toolkit/kernel.rs
- rusty-machine/src/learning/toolkit/rand_utils.rs
- rusty-machine/src/learning/toolkit/regularization.rs
- rusty-machine/src/lib.rs
- rusty-machine/src/linalg/convert.rs
- rusty-machine/src/linalg/macros.rs
- rusty-machine/src/linalg/matrix/decomposition.rs
- rusty-machine/src/linalg/matrix/impl_ops.rs
- rusty-machine/src/linalg/matrix/iter.rs
- rusty-machine/src/linalg/matrix/mat_mul.rs
- rusty-machine/src/linalg/matrix/mod.rs
- rusty-machine/src/linalg/matrix/slice.rs
- rusty-machine/src/linalg/utils.rs
- rusty-machine/src/linalg/vector.rs
- rusty-machine/src/prelude.rs
- rusty-machine/src/stats/dist/exponential.rs
- rusty-machine/src/stats/dist/gaussian.rs
This was originally meant to be a small commit on master. But ended up being quite a bit larger..
I'll review the diff and merge if there are no functional changes.
> Running clippy and rustfmt!

- src/learning/k_means.rs
- tests/learning/k_means.rs
There was a bug that made k-means almost totally broken...
Fixed the bug and added a new test which has a better chance of catching such breakage in future.
> Fixing centroid update step

- src/data/transforms/minmax.rs
- src/data/transforms/mod.rs
- src/data/transforms/standardize.rs
- src/learning/error.rs
- src/lib.rs
This is a work in progress but I'm opening for feedback now. This will eventually resolve #112 .
In order to complete this PR I need to do the following:
- Implement a scaler for zero centering and unit variance.
- Add error handling in min/max case when column is a constant feature. I think for now just fail gracefully..?
- Add better documentation and review module layout.
> Adding data transformers for preprocessing

- src/learning/optim/grad_desc.rs
- tests/learning/optim/grad_desc.rs
I added [RMSProp](http://sebastianruder.com/optimizing-gradient-descent/index.html#rmsprop) as another gradient descent algorithm. I think I have heard that it has become a popular optimization algorithm recently, so I thought it would nice to add. I tested it on the simple model in the tests folder, and on the neural network example.
> Implemented RMSProp Algorithm

- benches/examples/k_means.rs
- benches/examples/nnet.rs
- benches/examples/svm.rs
I'll remove these changes from pull request https://github.com/AtheMathmo/rusty-machine/pull/136.
> Fix warnings in benches

- src/learning/error.rs
- src/learning/gmm.rs
I was running into some problems, thought perhaps fixing this issue would fix my problems. Didn't work, but here's a fix for #119 anyway.
> Fix #119: Calculate sample covariance for GMM

- CHANGELOG.md
- CONTRIBUTING.md
- Cargo.toml
- DEVELOPMENT.md
- README.md
Making a PR for this as I've made quite a few changes to the markdown docs.
This includes changes from @theotherphil , @NivenT , and @andrewcsmith . If each of you could take a look and make sure I haven't missed anything I'd appreciate it!
If anyone has the patience to check the copy changes that would be great too!
> 0.5.0 version release

- src/learning/gmm.rs
> `LearningResult` as return type of `membership_weights` in GMM

- src/learning/gmm.rs
The regularization constant was already used properly in the initialization I wrote earlier.
> Issue #152: Only add regularization constant to diagonal

- Cargo.toml
> BUMP: Update rulinalg 0.3.7

- src/analysis/score.rs
Added ``precision``, ``recall`` and ``f1`` which is commonly used for classification tasks.
> ENH: Add classification scores

- src/data/transforms/minmax.rs
- src/data/transforms/mod.rs
- src/data/transforms/normalize.rs
- src/data/transforms/shuffle.rs
- src/data/transforms/standardize.rs
> Splitting out the Transformer trait

- src/analysis/confusion_matrix.rs
- src/analysis/cross_validation.rs
- src/learning/gmm.rs
- src/learning/k_means.rs
- src/learning/knn/binary_tree.rs
- src/learning/knn/brute_force.rs
- src/learning/knn/mod.rs
- src/learning/naive_bayes.rs
- src/learning/optim/fmincg.rs
- src/learning/toolkit/rand_utils.rs
> accept some Clippy suggestions

- Cargo.toml
> bump rand/num dependencies

- src/learning/optim/grad_desc.rs
- tests/learning/optim/grad_desc.rs
> Nesterov Momentum
